export enum RoleName {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  HOTEL_ADMIN = 'HOTEL_ADMIN',
  HOTEL_MANAGER = 'HOTEL_MANAGER',
  HOTEL_DEPARTMENT_MANAGER = 'HOTEL_DEPARTMENT_MANAGER',
  HOTEL_RECEPTIONIST = 'HOTEL_RECEPTIONIST',
  HOTEL_ACCOUNTANT = 'HOTEL_ACCOUNTANT',
  RESTAURANT_CACHIER = 'RESTAURANT_CACHIER',
  BAR_CACHIER = 'BAR_CACHIER',
  COFFEE_SHOP_CACHIER = 'COFFEE_SHOP_CACHIER',
  USER = 'USER',
}
